[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "minismtpd"
version = "0.1"
authors = [{ name = "Pēteris Caune", email = "cuu508@monkeyseemonkeydo.lv" }]
description = "A minimal SMTP server"
readme = "README.md"
requires-python = ">=3.12"
keywords = ["smtp"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

[project.urls]
Repository = "https://github.com/cuu508/minismtpd.git"
Issues = "https://github.com/cuu508/minismtpd/issues"

[tool.setuptools]
packages = ["minismtpd"]